language: node_js
node_js:
  - 12

before_install:
  - sudo apt-get install libavcodec-dev libavformat-dev libavdevice-dev libavfilter-dev libavutil-dev libpostproc-dev libswresample-dev libswscale-dev

deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release